project:
  name: quickstart-ct-new-relic-one
  owner: quickstart@amazon.com
  package_lambda: false
tests:
  newrelic-onboarding-us-west-2:
    parameters:
      NewRelicAccountNumber: ''
      LaunchAccountList: ''
      NewRelicAccessKey: ''
      StackSetName: 'NewRelic-Integration'
      StackSetUrl: 'https://newrelic-aws-quickstart.s3.amazonaws.com/control-tower/templates/newrelic-stack-set.yml'
    regions:
      - us-west-2
    template: control-tower-customization.yml